### ISSUE TITLE
如何快速入门Rust?

### ISSUE THREAD

**Issue by Palette25** [earn-me-some-money/emtm-web#1]
Rust学习曲线是否过于陡峭？

**Comment by miguch** [comment]
The official book [The Rust Programming Language](https://rustlang-cn.org/office/rust/book/) is great for quickly getting your hands dirty. Also, you can get familiar with most basic concepts by following [Learning Rust With Entirely Too Many Linked Lists](https://cglab.ca/~abeinges/blah/too-many-lists/book/README.html).
